# Generated by Django 3.0.2 on 2020-03-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAPP', '0003_remove_librariesclass_books_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksclass',
            name='image',
            field=models.ImageField(blank=True, height_field=300, upload_to='books_images', width_field=200),
        ),
    ]
