# Generated by Django 3.0.2 on 2020-03-17 10:55

import booksAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAPP', '0004_booksclass_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsclass',
            name='year_of_birth',
            field=models.DateField(validators=[booksAPP.models.is_valid_birth]),
        ),
        migrations.AlterField(
            model_name='booksclass',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to='books_images'),
        ),
        migrations.AlterField(
            model_name='booksclass',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='booksclass',
            name='pub_date',
            field=models.DateField(validators=[booksAPP.models.is_valid_pub]),
        ),
        migrations.AlterField(
            model_name='citiesclass',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='genreclass',
            name='features',
            field=models.TextField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='genreclass',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='librariesclass',
            name='address',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='librariesclass',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
