# Generated by Django 3.0.2 on 2020-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAPP', '0006_auto_20200317_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksclass',
            name='image',
            field=models.ImageField(default='default.png', upload_to='books_images'),
        ),
    ]
