# Generated by Django 3.0.2 on 2020-05-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAPP', '0007_auto_20200317_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksclass',
            name='av_in_libs',
            field=models.ManyToManyField(to='booksAPP.LibrariesClass'),
        ),
        migrations.AlterField(
            model_name='booksclass',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='books_images'),
        ),
    ]
