# Generated by Django 3.0.2 on 2020-02-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsClass',
            fields=[
                ('authorID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('second_name', models.CharField(max_length=40)),
                ('third_name', models.CharField(blank=True, max_length=40)),
                ('year_of_birth', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BooksClass',
            fields=[
                ('bookID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('info_about_book', models.TextField(blank=True, max_length=500)),
                ('authorID', models.ForeignKey(default="Author wasn't mentioned", null=True, on_delete=django.db.models.deletion.SET_NULL, to='booksAPP.AuthorsClass')),
            ],
        ),
        migrations.CreateModel(
            name='CitiesClass',
            fields=[
                ('cityID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='GenreClass',
            fields=[
                ('genreID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('features', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LibrariesClass',
            fields=[
                ('libraryID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=60)),
                ('num_of_books', models.BigIntegerField(default=0)),
                ('books_list', models.ManyToManyField(to='booksAPP.BooksClass')),
                ('cityID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booksAPP.CitiesClass')),
            ],
        ),
        migrations.AddField(
            model_name='booksclass',
            name='genreID',
            field=models.ForeignKey(default="Genre wasn't mentioned", null=True, on_delete=django.db.models.deletion.SET_NULL, to='booksAPP.GenreClass'),
        ),
    ]
